# This file is necessary for the build system as it specifies the build-time
# dependencies.
# You need to keep it in sync with development dependencies specified in
# Pipfile.
[build-system]
requires = [
  "Cython==3.*",
  "numpy==1.26.*",
  "setuptools",
]
