name: Build
on: [push, pull_request]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Supported runners: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        os: [ubuntu-22.04, windows-2022, macOS-13]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.1

      - name: Install codec2 on Ubuntu
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-22.04" ]; then
            sudo apt-get update -q
            sudo apt-get install -y codec2  # Install codec2 package on Ubuntu
          fi

      - name: Install codec2 on macOS
        run: |
          if [ "${{ matrix.os }}" == "macOS-13" ]; then
            brew update
            brew install codec2  # Install codec2 package on macOS
          fi

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
